# Generated by Django 4.2 on 2023-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LoginMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "support",
                    models.CharField(
                        choices=[
                            (
                                "بخش مالی (فاکتور/پیش فاکتور/بازگشت وجه)",
                                "بخش مالی (فاکتور/پیش فاکتور/بازگشت وجه)",
                            ),
                            (
                                "خدمات پس از فروش (بازکشت کالا)",
                                "خدمات پس از فروش (بازکشت کالا)",
                            ),
                            ("پشتیبانی", "پشتیبانی"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("کم", "کم"),
                            ("متوسط", "متوسط"),
                            ("فوری", "فوری"),
                            ("بحرانی", "بحرانی"),
                        ],
                        max_length=255,
                    ),
                ),
                ("file_field", models.FileField(upload_to="")),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
